Talon srx drivetrain shuffleboard
BHSRobotix/RapidReact2022 pull request #22
Opened 2022-02-15 13:16 UTC by loafdog

2022-02-15 15:31 UTC, slyafwalrus approved these changes

2022-02-15 16:06 UTC, ParkerMeyers requested changes
There seems to be a lot of temporary code or code that was marked for removal. If this test code is needed, leave a comment and ill re-review, otherwise, make sure to remove it before merging.

2022-02-15 16:06 UTC, ParkerMeyers commented on src/main/java/bhs/devilbotz/subsystems/DriveTrain.java
> +    public double test(){
Temporary code? Is this needed or called upon anywhere?

2022-02-15 16:06 UTC, ParkerMeyers commented on src/main/java/bhs/devilbotz/subsystems/DriveTrain.java
> +    // TODO: Remove
This code is marked for removal, if it is not needed, then please remove it, otherwise disregard this message.

2022-02-15 16:06 UTC, ParkerMeyers commented on src/main/java/bhs/devilbotz/subsystems/TalonSrxDiagnostic.java
> +//   private static final WPI_TalonSRX rightFollower = new WPI_TalonSRX(3);
Please remove commented out code, the Talons are also already defined in the drive train, so there is no need for this either.

2022-02-15 16:06 UTC, ParkerMeyers commented on src/main/java/bhs/devilbotz/subsystems/TalonSrxDiagnostic.java
> +    //     return rightFollower.getMotorOutputVoltage();
Please remove commented out code unless it is needed!

2022-02-17 01:06 UTC, adipraj17 commented
resolved in person

2022-02-17 01:11 UTC, ParkerMeyers reviewed
Still some changes to be made, some formatting error.

2022-02-17 01:11 UTC, ParkerMeyers commented on src/main/java/bhs/devilbotz/subsystems/DriveTrain.java
> +     * Gets the NAVXF
Fix Grammer Errors

2022-02-17 01:11 UTC, ParkerMeyers commented on src/main/java/bhs/devilbotz/subsystems/DriveTrain.java
> +    }
Temporary code? Is this needed or called upon anywhere? If not, please remove before merging.

2022-02-17 01:11 UTC, ParkerMeyers commented on src/main/java/bhs/devilbotz/subsystems/DriveTrain.java
> +    // }
Still marked for removal, if it is not needed, then please remove it, otherwise disregard this message.

2022-02-17 01:15 UTC, ParkerMeyers approved these changes
Nice revisions!

2022-02-17 01:16 UTC, merged